apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netology
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: packages/app/prod
    repoURL: 'https://gitlab.com/devops-diploma-public/netology-app/cluster-repo.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
